#ifndef INSTRUMENT_LUT_H
#define INSTRUMENT_LUT_H

// This file is auto-generated by instrument_lut_gen.py -- do not edit directy

const int NUM_CATEGORIES = 6;
const int NUM_INSTRUMENTS = 28;

const char *INSTRUMENT_CAT_ID_TO_NAME_LUT[6] = {
  "chants",
  "hihats",
  "claps",
  "snares",
  "shakers",
  "kicks",
}; // lut[cat_id] = instrument category name

const char *INSTRUMENT_ID_TO_NAME_LUT[28] = {
  "hey",
  "woo",
  "hoo",
  "hihat4",
  "edm2",
  "edm1",
  "trap3",
  "trap2",
  "trap1",
  "edm1",
  "group",
  "clap1",
  "clap3",
  "clap2",
  "bongo1",
  "skin1",
  "edm2",
  "edm1",
  "trap1",
  "shaker1",
  "christmas1",
  "skin1",
  "edm1",
  "hard2",
  "kick2",
  "kick3",
  "hard1",
  "kick1",
}; // lut[instrument_id] = instrument name

const int INSTRUMENT_CAT_INFO_LUT[6][2] = {
 {0, 3},
 {3, 6},
 {9, 5},
 {14, 5},
 {19, 2},
 {21, 7},
}; // lut[cat_id][0] = starting instrument ID, lut[cat_id][1] = number of instruments in category

const char *ABSOLUTE_PATHS[28] = {
  "/Users/micahreich/Documents/FinalHack/instruments/chants/hey.wav",
  "/Users/micahreich/Documents/FinalHack/instruments/chants/woo.wav",
  "/Users/micahreich/Documents/FinalHack/instruments/chants/hoo.wav",
  "/Users/micahreich/Documents/FinalHack/instruments/hihats/hihat4.wav",
  "/Users/micahreich/Documents/FinalHack/instruments/hihats/edm2.wav",
  "/Users/micahreich/Documents/FinalHack/instruments/hihats/edm1.wav",
  "/Users/micahreich/Documents/FinalHack/instruments/hihats/trap3.wav",
  "/Users/micahreich/Documents/FinalHack/instruments/hihats/trap2.wav",
  "/Users/micahreich/Documents/FinalHack/instruments/hihats/trap1.wav",
  "/Users/micahreich/Documents/FinalHack/instruments/claps/edm1.wav",
  "/Users/micahreich/Documents/FinalHack/instruments/claps/group.wav",
  "/Users/micahreich/Documents/FinalHack/instruments/claps/clap1.wav",
  "/Users/micahreich/Documents/FinalHack/instruments/claps/clap3.wav",
  "/Users/micahreich/Documents/FinalHack/instruments/claps/clap2.wav",
  "/Users/micahreich/Documents/FinalHack/instruments/snares/bongo1.wav",
  "/Users/micahreich/Documents/FinalHack/instruments/snares/skin1.wav",
  "/Users/micahreich/Documents/FinalHack/instruments/snares/edm2.wav",
  "/Users/micahreich/Documents/FinalHack/instruments/snares/edm1.wav",
  "/Users/micahreich/Documents/FinalHack/instruments/snares/trap1.wav",
  "/Users/micahreich/Documents/FinalHack/instruments/shakers/shaker1.wav",
  "/Users/micahreich/Documents/FinalHack/instruments/shakers/christmas1.wav",
  "/Users/micahreich/Documents/FinalHack/instruments/kicks/skin1.wav",
  "/Users/micahreich/Documents/FinalHack/instruments/kicks/edm1.wav",
  "/Users/micahreich/Documents/FinalHack/instruments/kicks/hard2.wav",
  "/Users/micahreich/Documents/FinalHack/instruments/kicks/kick2.wav",
  "/Users/micahreich/Documents/FinalHack/instruments/kicks/kick3.wav",
  "/Users/micahreich/Documents/FinalHack/instruments/kicks/hard1.wav",
  "/Users/micahreich/Documents/FinalHack/instruments/kicks/kick1.wav",
}; // lut[instrument_id] = absolute filepath to .wav sample

#endif
