#ifndef INSTRUMENT_LUT_H
#define INSTRUMENT_LUT_H

// This file is auto-generated by instrument_lut_gen.py -- do not edit directy

const int NUM_CATEGORIES = 4;
const int NUM_INSTRUMENTS = 4;

const char *INSTRUMENT_CAT_ID_TO_NAME_LUT[4] = {
  "hihats",
  "claps",
  "snares",
  "kicks",
}; // lut[cat_id] = instrument category name

const char *INSTRUMENT_ID_TO_NAME_LUT[4] = {
  "hihat1",
  "clap1",
  "kick2",
  "kick1",
}; // lut[instrument_id] = instrument name

const int INSTRUMENT_CAT_INFO_LUT[4][2] = {
 {0, 1},
 {1, 1},
 {2, 0},
 {2, 2},
}; // lut[cat_id][0] = starting instrument ID, lut[cat_id][1] = number of instruments in category

const char *ABSOLUTE_PATHS[4] = {
  "/Users/micahreich/Documents/FinalHack/instruments/hihats/hihat1.wav",
  "/Users/micahreich/Documents/FinalHack/instruments/claps/clap1.wav",
  "/Users/micahreich/Documents/FinalHack/instruments/kicks/kick2.wav",
  "/Users/micahreich/Documents/FinalHack/instruments/kicks/kick1.wav",
}; // lut[instrument_id] = absolute filepath to .wav sample

#endif
